site_name: Ballerina Documentation
repo_url: https://github.com/ballerinalang/ballerina
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2017 WSO2, Inc.
pages:
- Get Started:
    - Welcome: 'index.md'
    - Quick Tour: 'quick-tour.md'
    - Write your First Program: 'tutorials/first-program.md'
    - Key Concepts: 'key-concepts.md'
    - Tools: 'tools.md'
    - Samples: 'samples.md'
- Language Reference:
    - Overview: 'lang-ref/lang-overview.md'
    - Packaging and Running Programs: 'lang-ref/packaging.md'
    - Services: 'lang-ref/services.md'
    - Resources: 'lang-ref/resources.md'
    - Functions: 'lang-ref/functions.md'
    - Actions: 'lang-ref/actions.md'
    - Workers: 'lang-ref/workers.md'
    - Types and Variables: 'lang-ref/types-variables.md'
    - Statements: 'lang-ref/statements.md'
    - Exception Handling: 'lang-ref/exceptions.md'
- Connectors: 
    - Working with Connectors: 'lang-ref/connectors.md'
    - File Server Connector: 'server-connectors/file-server.md'
    - HTTP/2 Server Connector: 'server-connectors/http2-server.md'
    - JMS Client Connector: 'server-connectors/jms-client.md'
    - JMS Server Connector: 'server-connectors/jms-server.md'
    - WebSocket Server Connector: 'server-connectors/websocket-server.md'    
- Additional Reference:
    - API Documentation: 'native-functions.md'
    - Language Specification: 'spec.md'
    - Architecture Design Documents: 'architecture.md'
theme_dir: docs/ballerina-theme
theme: null
extra_css:
    - ballerina-theme/css/ballerina.css
    - ballerina-theme/css/highlight.css
    - ballerina-theme/css/theme.css
    - ballerina-theme/css/theme_extra.css
extra_javascript:
    - ballerina-theme/js/highlight.pack.js
    - ballerina-theme/js/jquery-2.1.1.min.js
    - ballerina-theme/js/modernizr-2.8.3.min.js
    - ballerina-theme/js/theme.js
